### ISSUE TITLE
fatal: could not read Username

### ISSUE THREAD

**Issue by kurtmaile** [dharnitski/golang-codebuild#2]
Hi I am trying to use codebuild to build my serverless project - I followed the AWS example at first so slightly different this which I found today.  My repos are private in giuthub NOT codecommit, and I seem to have issues with go get?

Codebuild has a key to access the repos - it clones the master repo fine.  However the gogets cause me the issuein the buildspec.yml, I get below error at the line cd /go/src/${PACKAGE} && go get ./...:

Cloning into '/go/src/github.com/xxxxx..
fatal: could not read Username for 'https://github.com/xxxxx': No such device or address

```
phases:
  install:
    commands:
      # AWS Codebuild Go images use /go for the $GOPATH so copy the
      # application source code into that directory structure.
      - mkdir -p "/go/src/$(dirname ${PACKAGE})"
      - ln -s "${CODEBUILD_SRC_DIR}" "/go/src/${PACKAGE}"
      # Print all environment variables (handy for AWS CodeBuild logs)
      - env

  pre_build:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
      # Make sure we're in the project directory within our GOPATH
      # Fetch all dependencies
      - cd /go/src/${PACKAGE} && go get ./...

  build:
    commands:
      # CD to the scripts dir
      - cd "/go/src/${PACKAGE}/${SCRIPTS_DIR}"
      # Build the go application
      - ./build-all-go.sh ${ENV}
      # Package the application with AWS SAM
      - ./package-stack ${ENV} ${BRANCH}
```
Ive seen some posts to add below but it references codecommit - have you run into this before?  Any ideas?  thanks!

- git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
